# Build stage
FROM node:22.1.0 AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY ./prisma ./prisma

RUN npm install

COPY . .

RUN npm run db:gen-dto
RUN npm run build

# Production stage
FROM node:22.1.0-alpine

WORKDIR /app

COPY package*.json ./
COPY ./prisma ./prisma

RUN npm install --production && npm install resend

COPY --from=builder /app/dist /app/dist

EXPOSE 3000

CMD ["node", "dist/app.js"]